Extended AbstractTransformer and Models
Insly/qmt-api-php-client pull request #4
Opened 2022-10-21 21:36 UTC by taron-insly

## Please ignore branch name, initially it was created only for vehicles api :)

- Added relation transformer
- Added custom transformer functionality per field
- Improved QmtServiceEndpoint for Quotes
- Separated Quote Motor product
- Added some fields for Vehicles
- Added some fields for Quote
- Added some fields for Customer
- Style fixes

### TODO
- **Add participants api**
- Add/Update Tests
- Add delete ???

2022-10-24 10:14 UTC, AkselMeola requested changes

2022-10-24 10:14 UTC, AkselMeola commented on src/Api/Transformers/Qmt/Quote/MotorTransformer.php
> +class MotorTransformer extends AbstractTransformer
I think all Quotes could be transformed with this transformer. Avoid making product specific transformers since we will have hard time supporting all additional products in this library.

2022-10-24 10:14 UTC, AkselMeola commented on src/Api/Endpoints/QmtServiceEndpoint.php
> +                (new VehicleTransformer())->reverseTransform($vehicle->getFields())
Could make a factory to load object transformer based on object tag. So for vehicle and participant there would be custom transformer with added fields and default would be some default generic object transformer.

2022-10-24 10:14 UTC, AkselMeola commented on tests/unit/Transformers/CustomerTest.php
> -<?php
Why this test was removed ?

2022-10-24 12:52 UTC, taron-insly commented on run_ecs_check.sh
>  $DOCKER_CMD run --init --rm -it \
Why? BASE_CMD and DOCKER_CMD both has usage

2022-10-24 13:03 UTC, taron-insly commented on src/Api/Endpoints/QmtServiceEndpoint.php
> +    public function quote(string $productType): MotorEndpoint
I agree that method `quote()` should return not `MotorEndpoint()` but `QuoteEndpoint()` and based on product type it can be as `Quote\MotorEndpoint` as `Quote\TravelEndpoint`.
Connected with separations of quote per products: they don't have any common thing, all fields and mappers are differ, that's why I separated them.

2022-10-24 13:09 UTC, taron-insly commented on src/Api/Endpoints/QmtServiceEndpoint.php
> +    public function vehicleList(array $queryParams = []): VehicleListResponse
I would suggest to have `object(string $tag)` which will return appropriate endpoint for each object.
Such as objects in their logic and fields are differ (e.g. participant and vehicle have different fields/relations and transformers) it's more comfortable to have separated them all. Like for quotes I am sure that in most cases we need to separate everything with switch case, so why not to have separate endpoints. Also there are object specific endpoints also.

2022-10-24 13:12 UTC, taron-insly commented on src/Api/Transformers/Qmt/Quote/MotorTransformer.php
> +class MotorTransformer extends AbstractTransformer
I think in most cases we will override common transformer, but agree that make sense to have common transformer and why not model for quotes and objects.

2022-10-24 13:13 UTC, taron-insly commented on tests/unit/Transformers/CustomerTest.php
> -<?php
Because it contains only relation transformer methods written for customer transformer, but now common relation method added in abstract transformer

2022-10-25 09:37 UTC, AkselMeola commented on tests/unit/Transformers/CustomerTest.php
> -<?php
The result of customer transfomer should be same either way.

2022-10-25 09:51 UTC, AkselMeola commented on tests/unit/ClientTest.php
> +            $client->qmt()->quotes(BaseQuote::PRODUCT_TYPES['motor'])->get('some-id');
Probably better to use constant for 'motor' instead.

2022-10-25 12:34 UTC, taron-insly commented on tests/unit/ClientTest.php
> +            $client->qmt()->quotes(BaseQuote::PRODUCT_TYPES['motor'])->get('some-id');
Done

2022-10-25 12:34 UTC, taron-insly commented on tests/unit/Transformers/CustomerTest.php
> -<?php
Reverted back and renamed methods

2022-10-25 12:35 UTC, taron-insly commented on src/Api/Endpoints/QmtServiceEndpoint.php
> +                (new VehicleTransformer())->reverseTransform($vehicle->getFields())
Changed to return object endpoint class (for participant and vehicle methods are differ).
General object case will be covered out of this task.

2022-10-25 12:38 UTC, taron-insly commented on src/Api/Transformers/Qmt/Quote/MotorTransformer.php
> +class MotorTransformer extends AbstractTransformer
Created base quote transformer and model. After for each new type of Quote we need to create only model and transformer with correct naming (and add appropriate `const` in `BaseQuote` model), other part will be handled automatically.

2022-10-25 12:40 UTC, taron-insly commented on src/Api/Endpoints/Qmt/Quote/MotorEndpoint.php
> +                $this->tenantPath('/p/motor/quotes'),
Done, now you can use `qmt()->quotes(string $productType)->get(string $id)`, `qmt()->quotes(string $productType)->list()`, ...

2022-10-25 12:51 UTC, taron-insly commented on src/Api/Endpoints/QmtServiceEndpoint.php
> +    public function quote(string $productType): MotorEndpoint
Fixed

2022-11-07 14:22 UTC, AkselMeola requested changes

2022-11-07 14:22 UTC, AkselMeola commented on src/Api/Endpoints/Qmt/Quotes/QuoteEndpoint.php
> +            throw new \InvalidArgumentException('Invalid product type is provided: ' . $productType);
What if we add a new product? Then we need to come here and update the list of quote products. Let the API handle the wrong/correct product types. If wrong is provided, then an error is thrown. Client just translates the request, API does the validation and hard work.

2022-11-07 14:22 UTC, AkselMeola commented on src/Api/Endpoints/Qmt/Quotes/QuoteEndpoint.php
> +        $class = '\Insly\QmtApiClient\Api\Models\Qmt\Quotes\\' . ucfirst($productType);
The same as with $productTag. In my understanding, there is nothing that different types of Quotes can provide in transformation. All quotes have the same structure. 

All quotes have the subsection "objects". and that array contains the list of objects keyed by object tag. 
Since the `relations()` provides no typehinting anyway,  I'd do the whole objects transformation there. 
Vehicles and Participants could have a class_exists() check and all the other objects would use some general object transformer, since they are also all the same. 

This way we handle our special cases and new quotes and objects would need little to no maintenance - except new added fields.

2022-11-08 12:09 UTC, taron-insly commented on src/Api/Endpoints/Qmt/Quotes/QuoteEndpoint.php
> +            throw new \InvalidArgumentException('Invalid product type is provided: ' . $productType);
Removed

2022-11-08 12:13 UTC, taron-insly commented on src/Api/Endpoints/Qmt/Quotes/QuoteEndpoint.php
> +        $class = '\Insly\QmtApiClient\Api\Models\Qmt\Quotes\\' . ucfirst($productType);
Added BaseQuote and BaseObject models and transformers, so if there is not separate class for them, base will be used.
For vehicle and participant uses separate endpoint classes which inherit base object endpoint, for other object tags uses general object endpoint (which also inherits base object endpoint)

2022-11-08 12:14 UTC, AkselMeola approved these changes

2022-11-09 13:02 UTC, stasmajevski requested changes

2022-11-09 13:10 UTC, taron-insly commented on src/Api/Models/Qmt/Objects/BaseObject.php
> +    public const TAG_SAMPLE = 'sample';
removed

2022-11-09 13:12 UTC, stasmajevski approved these changes

2022-11-09 14:01 UTC, merged